---
version: '3.8'
services:

  prd-rtsp-server-app:
    image: docker-registry.theautomation.nl/coen/prd-rtsp-server-app:latest
    container_name: prd-rtsp-server-app
    restart: always
    ports:
      - 8554:8554
      - 1935:1935
    networks:
      - rtsp-server
    volumes:
      - ./config/rtsp-simple-server.yml:/rtsp-simple-server.yml

networks:
  rtsp-server:
    name: rtsp-server
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
